name: auction-web

services:
  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  database_data: null
